### ISSUE TITLE
Translation updates via translatewiki.net

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#10]
It will be nice to get translation updates via translatewiki.net

- [x] Fluff "qqq.json" - done via https://github.com/oetterer/BootstrapComponents/pull/11
- [x] Grant push rights to @translatewiki
- [x] Ping @nikerabbit

**Comment by oetterer** [comment]
I added @translatewiki as collaborator a few weeks ago, invite is still pending. What else should I do?

**Comment by kghbln** [comment]
Just ping @nikerabbit He will do the rest.

**Comment by oetterer** [comment]
Okay. :) Here's to hoping @Nikerabbit comes to the rescue! :)

**Comment by kghbln** [comment]
Well @nikerabbit got four pings now. That's on the brink of being spam. :D

**Comment by Nikerabbit** [comment]
More than four (I also read translatewiki's).

I have accepted the invite now. I was not sure before what it was related to.

Does someone fancy making a patch in gerrit akin to wikimedia/translatewiki@322b2324c1d213bfaca6e123ec0302cc51629a78?

**Comment by oetterer** [comment]
Gerrit and I are not on the best of terms, but here is my take on it: https://gerrit.wikimedia.org/r/#/c/412940/

**Comment by oetterer** [comment]
And now I have my next gerrit foobar (I think). I tried to fix the incorrect use of a tab and got https://gerrit.wikimedia.org/r/#/c/412943/

**Comment by oetterer** [comment]
The patch is merged. Do I have to do anything else?

**Comment by kghbln** [comment]
> Do I have to do anything else?

No, just wait for the translations to roll in and after a month and make a minor release to get these officially to the public. You may close this one now. :)
