### ISSUE TITLE
Modal popup <DIV> not generated

### ISSUE THREAD

**Issue by imyopop** [oetterer/BootstrapComponents#12]
### Setup and configuration

- MW version: 1.30.0
- PHP: 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)
- DB (MySQL etc.): 10.0.34-MariaDB-0ubuntu0.16.04.1
- Skin (version): Chameleon 1.6
- Bootstrap: 1.2.3
- BootstrapComponents: 1.21

### Issue
Attempting to use a Modal generated via a template. In one case it works, in another it doesn't generate the <div> that contains the modal information.
Here is the case that works: https://ddocompendium.com/w/Template:QuestTrap
Here is the case that doesn't generate the div: https://ddocompendium.com/w/Sacrifices

Not sure if I am missing something.  I did verify that the HTML is correct.

**Comment by imyopop** [comment]
Ok, I created a very paired down sample where it doesn't work.  It seems to have an issue when DynamicPageList3 is used and a result is generated.  Here is the template: https://ddocompendium.com/w/User:MNDeveloper/Template:Quest

Here is the usage where it works, and DPL doesn't generate any results: https://ddocompendium.com/w/User:MNDeveloper/SampleQuest2

Here is where it doesn't work, and DPL does generate results.
https://ddocompendium.com/w/User:MNDeveloper/SampleQuest

Now, if I put the DPL run before the modal, it works in both cases.

**Comment by imyopop** [comment]
We had to roll back the php version for another DPL issue - we are now on 7.0.30-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)

**Comment by kghbln** [comment]
Thanks for reporting. Ping @oetterer

**Comment by oetterer** [comment]
Yeah. Thank you very much. I'm on the road for a few days but will have a look at it next week when I'm back.

**Comment by oetterer** [comment]
update: started working on the problem. first results:
* I was able to reproduce it on my dev system. 
* it seems to be unrelated to the mw version, since it also occurs on 1.27

tbc...

**Comment by oetterer** [comment]
Looks like the hook I use to insert the modal was a too convenient choice and has some unforseen side effects. I now have an idea, how to fix this though.

**Comment by oetterer** [comment]
@imyopop sorry it took so long. Unfortunately, you uncovered a conceptual error and not a normal bug. Modals now should work together with DPL, please use version **1.2.2**.

Thanks again for reporting this problem!
