### ISSUE TITLE
Going Twitter Bootstrap 4

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#13]
Stephan has recently started to switch the [Chameleon skin](https://github.com/cmln/chameleon) to use Twitter Bootstrap 4 and has already release a stable version of the [Bootstrap extension](https://github.com/cmln/mw-bootstrap) shipping Twitter Bootstrap 4. I guess it will be great to also get this extension to be compatible with Twitter Bootstrap 4.

@s7eph4n FYI

**Comment by keesh7663** [comment]
Wondering if any work has been done on this? Would be nice to have for sure

**Comment by oetterer** [comment]
Release is scheduled for January 2020. Sry for the delay.

**Comment by keesh7663** [comment]
hi @oetterer, just wondering if there is any status for this update? haven't seen a push in a while

**Comment by oetterer** [comment]
yeah. sorry for that. current crisis hit me in the middle of updating to bs4. Functionality is almost done. Missing documentation, as usual.

**Comment by oetterer** [comment]
@keesh7663, @kghbln sorry for the delay. BSC is now Bootstrap4 compatible. It also provides some downward compativilty for components that have been removed by twitter during the transition. Please read the migration guide in the provided documentation.

closed as of #16

**Comment by kghbln** [comment]
@oetterer Thanks a ton. I have just re-installed the extension on sandbox but have not had a look [which examples](https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:Bootstrap_Components_examples) went bellies up.
