### ISSUE TITLE
Switch to manual invocation with Composer

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#14]
### Setup and configuration

- MediaWiki | 1.31.1 (f1e85dd)16:50, 25 April 2019
- PHP | 7.2.17-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.1
- Chameleon | 1.7.1 (5b963c3) 20:32, 10 May 2018
- Bootstrap | 1.3.0 (ea33f24) 10:57, 15 January 2019
- BootstrapComponents | 1.2.3 (254874f) 11:28, 28 September 2018

### Issue

Currently when installed with Composer the extension is automatically being loaded for usage on the wiki. A "recent" trend is to switch to manual invocation of an extension e.g. with:
```php
wfLoadExtension( 'BootstrapComponents' );
```
even if it is installed with Composer. The Bootstrap extension now works like this with the recent release and the Chameleon skin will afaik also switch. Thus I believe it will be nice if this extension switched too as soon as #13 is implemented.

**Comment by oetterer** [comment]
implemented as of #16
