### ISSUE TITLE
Not possible to use new theme-color

### ISSUE THREAD

**Issue by DesignerThan95** [oetterer/BootstrapComponents#19]
### Setup and configuration

- MW version: 1.35 
- PHP: 7.4.10 (fpm-fcgi)
- DB (MySQL etc.): 5.7.28-nmm1-log
- Skin (version): Chameleon (3.1.0
- Bootstrap: 4.5.3
- BootstrapComponents: 4.0.0

### Issue

I have added a new theme-color to bootstrap. The problem now is, that if I use the create button function of this extension it checks the color if it is valid and as I have added it, it isn't. Now my question, why is it necessary to check the colors? Is there a good solution to get that going, instead of just adding the color to the array of valid once?

**Comment by DesignerThan95** [comment]
Sorry my mistake. I thought this extension uses the Bootstrap extension for the styles, but it doesn't. That it is why it does check the colors because it offers only the defined once in it's own stylesheet's.

**Comment by oetterer** [comment]
@DesignerThan95 the color attribute only uses the bootstrap default colors. the plausibility check is aimed to help assure, that no undefined value is used. Whey you add a new theme-color, does it add a new css-class? if so, you can use the class attribute.

**Comment by DesignerThan95** [comment]
The css-class gets created correctly. That is an idea, thanks. I have solved it, by implementing a config variable for the LocalSettings.php file, so I was able to add another color there.
If you like, I can try to share it in a pull-request.
