### ISSUE TITLE
Error from line 190 of ParserOutputHelper.php: Call to a member function getExtensionData() on null

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#20]
### Setup and configuration

- MW version: MediaWiki | 1.31.14 (7b0ec17)
- PHP: 7.0.33-0+deb9u10 (apache2handler)
- DB (MySQL etc.): 10.1.48-MariaDB-0+deb9u2
- Skin (version): 3.2.0 (fff48f0) 20:55, 18. Apr. 2021
- Bootstrap: 4.5.0
- BootstrapComponents: 4.0.0
- PageForms: 5.2.1

### Issue

When trying to upload a file via PageForms `{{{field |Datei |input type=text |uploadable }}}` I get the following error from the API:

```
2021-05-03 21:04:52 phalaris 4142720200705-41427_: [de1b397acec551818f97c56c] /w/api.php   Error from line 190 of /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php: Call to a member function getExtensionData() on null
```

**Comment by kghbln** [comment]
@oetterer It will be great if you could have a peep at this.

**Comment by oetterer** [comment]
@kghbln thanks for catching this. I think I got the error. Trying to fix some other travis problems along the way.

**Comment by kghbln** [comment]
Cool. I just saw https://github.com/oetterer/BootstrapComponents/pull/18 which could potentially be dealt with too at this point.
