### ISSUE TITLE
MediaWiki 1.35 deprecation notices

### ISSUE THREAD

**Issue by malberts** [oetterer/BootstrapComponents#22]
### Setup and configuration

- MW version: 1.35.2
- PHP: 7.4.19
- DB: SQLite 3.27.2
- Skin: Chameleon (master) | Vector (1.35.2)
- Bootstrap extension: 4.5.0 (=Bootstrap library 4.6.0)
- BootstrapComponents: master

### Issue

When setting `$wgDevelopmentWarnings = true;` in `LocalSettings.php` the following deprecation notices are printed at the top of all pages:

> Deprecated
> : Registering handler for OutputPageParserOutput before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430
> 
> Deprecated
> : Registering handler for ParserAfterParse before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430
> 
> Deprecated
> : Registering handler for ParserFirstCallInit before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430
> 
> Deprecated
> : Registering handler for ScribuntoExternalLibraries before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430
> 
> Deprecated
> : Registering handler for SetupAfterCache before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430
> 
> Deprecated
> : Registering handler for GalleryGetModes before MediaWiki bootstrap complete was deprecated in MediaWiki 1.35 [Called from BootstrapComponents\HookRegistry::register in /var/www/html/extensions/BootstrapComponents/src/HookRegistry.php at line 289] in
> /var/www/html/includes/debug/MWDebug.php
> on line
> 430

(Deprecated here: https://github.com/wikimedia/mediawiki/commit/0adc5f342888740e1b611f95f1474be329eae817#diff-67493378a23f7e46c2802428296557d6def299c21a84598f281d87ee7e0f2484R44)

**Comment by kghbln** [comment]
@oetterer Lots of cool momentum for this extension ... If you could have a peep. Thanks a ton!

**Comment by oetterer** [comment]
@kghbln really greatful for your poke!

**Comment by kghbln** [comment]
@oetterer You are welcome. Thanks for working on this extension!
