### ISSUE TITLE
Bootstrap Component with Templates

### ISSUE THREAD

**Issue by girls-whocode** [oetterer/BootstrapComponents#26]
### Setup and configuration

- MW version: 1.35.1
- PHP: 7.4.3
- DB (MySQL etc.): MariaDB
- Skin (version): 3.4.1
- Bootstrap: 4.5
- BootstrapComponents: 4.0.1

### Issue

No stacktrace available

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
Let's create a FAQ template

Start a normal page:
{{FAQ|q=How do I look|a=You look great}}

Creating the template FAQ
<bootstrap_card header={{{q}}}>{{{a}}}</bootstrap_card>

OR

<bootstrap_card header="{{{q}}}">{{{a}}}</bootstrap_card>

OR

<bootstrap_card header='{{{q}}}'>{{{a}}}</bootstrap_card>

It does not render the variable "q", although the "a" is working great.

**Comment by lyrixn** [comment]
Have you had any chance to tackle this?

**Comment by oetterer** [comment]
@lyrixn latest version should solve your problem, sorry it took so long.

**Comment by oetterer** [comment]
@girls-whocode latest version should solve your problem, sorry it took so long.

**Comment by lyrixn** [comment]
> @lyrixn latest version should solve your problem, sorry it took so long.

Works perfectly, thanks!
