### ISSUE TITLE
Pages using components changes the list style for "li"

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#28]
### Setup and configuration

- MediaWiki | 1.35.0-rc.2 (5f6c9d1)17:32, 21 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.9 (apache2handler)
- MariaDB | 10.1.48-MariaDB-0ubuntu0.18.04.1
- Medik | 3.2.0 (fff48f0) 20:55, 18 April 2021
- Bootstrap | 4.5.0 (608be3f) 01:07, 11 April 2021
- BootstrapComponents | 4.0.1 (98e179c) 22:36, 26 May 2021 |  

### Issue

Pages using components changes the list style for "li" (additional bullets). This happens with all components. See e.g. https://sandbox.semantic-mediawiki.org/wiki/BootstrapComponents/Carousel. This started with BS 4.

![Bildschirmfoto vom 2021-10-29 10-43-52](https://user-images.githubusercontent.com/1104078/139406289-92634be0-55ce-44a9-b24a-ee9c840f5c8c.png)

**Comment by malberts** [comment]
@kghbln  This seems to be another case of what I mentioned in https://github.com/oetterer/BootstrapComponents/issues/21#issuecomment-841733547
When Chameleon is available, but not active, it still loads some styles which causes problems when using Medik and BootstrapComponents.
Can you check if this goes away when you make Chameleon unavailable?

**Comment by kghbln** [comment]
@malberts

> This seems to be another case of what I mentioned in #21 (comment)

Forgot all about his one

>  Can you check if this goes away when you make Chameleon unavailable?

Affirmative, once I comment Chameleon the issue goes away.

![Bildschirmfoto vom 2021-10-30 10-47-07](https://user-images.githubusercontent.com/1104078/139526510-3bb62657-f425-4ec9-81b7-e490d606ffae.png)

Good to know why this is happening. Also since people will probably not have Medik and Chameleon on the same instance it now appears to be a back-burner issue. Still it will be great to have a fix for it.

**Comment by kghbln** [comment]
We can close this one. The solution is to not install the two skins in parallel. I reality, this is probably not often the case anyways.
