### ISSUE TITLE
card-img-top not placed correctly

### ISSUE THREAD

**Issue by Hasenhirn** [oetterer/BootstrapComponents#30]
### Setup and configuration

- MW version: 1.35.5
- PHP: 7.4.27
- DB (MySQL etc.): 10.6.5-MariaDB
- Skin (version): Chameleon 3.4.1
- Bootstrap: 4.5.0
- BootstrapComponents: 4.0.1
- Link_Attributes: 1.1

### Issue
- Missing card-img-top option
- Card Header Images not filling the whole heading, parser prepends div.card-header and puts Image in h4 container

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

The code below shows the different approaches. and Outcomes
```
<div class="row">
<div class="col-3">
<div class="card">[[Datei:180x100.png|class=card-img-top|alt=Card image cap]]
<div class="card-body">
<h5 class="card-title">Card title</h5>
<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
[[Hallo|Klick mich ((.btn .btn-primary))]]
</div>
</div>
</div>
<div class="col-3">
<bootstrap_card header="[[Datei:180x100.png|class=card-img-top|alt=Card image cap]]">
<h5 class="card-title">Card title</h5>
<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
[[Hallo|Klick mich ((.btn .btn-primary .text-white))]]
</bootstrap_card>
</div>
</div>
```
![2021-12-30 08_59_28-Window](https://user-images.githubusercontent.com/76073496/147732705-4facb4d8-8533-4625-8812-2f775774ae4a.png)

Possible solutions:

- Implement a seperate header_image attribute
- Check if [[File: is referenced in wiki markup and let the paser place the image accordingly

P.S.: Thank you very very much for your work!!!!

**Comment by oetterer** [comment]
hey @Hasenhirn. I followed your suggestion and added a header-image (and footer-image) attribute. Unfortunately, for now you need to supply the appropriate class manually.

ps: sorry, it took so long.

**Comment by oetterer** [comment]
@Hasenhirn its me again. Found a way to take care of the required css classes for footer and header images. no need to supply them.
