### ISSUE TITLE
Create release 5.2.0

### ISSUE THREAD

**Issue by malberts** [oetterer/BootstrapComponents#47]
Besides the other fixes since 5.1.1, the main reason is to include the newer version of the Bootstrap extension (https://github.com/oetterer/BootstrapComponents/commit/b8bd780564d4c13f553e4ee3239828d4c16af681) in a tagged release.

On the Chameleon/Bootstrap side we want to move ahead with dropping support for older versions of MW and PHP, but right now BootstrapComponents is going to prevent Composer from downloading Bootstrap extension 5.0.0.

This change doesn't cause backward incompatible issues for BootstrapComponents users, it just allows it to also work with the new MW 1.39 / PHP 8.0 only version of the Bootstrap extension.

@oetterer Did you have any other fixes or issues in mind for BootstrapComponents 5.2? I can go ahead and prepare a PR for the release if there are no blockers.

**Comment by oetterer** [comment]
@malberts thank you very much. I have nothing in the pipeline atm, go ahead!

**Comment by D3nnis3n** [comment]
I'm currently affected by BootstrapComponents blocking install of the 5.0@dev of chameleon (which is not released yet either, though).

**Comment by oetterer** [comment]
Working on this

**Comment by oetterer** [comment]
@D3nnis3n the current master is technically compatible with Bootstrap v5.0.0 which I recon you need for chameleon. If you check out the repo instead of using composer to install BootstrapComponents, you should be fine.

 I'm still working on incorporating the changes in the components that come with bootstrap5.

**Comment by malberts** [comment]
FYI The new [Bootstrap extension version 5.0.0](https://github.com/ProfessionalWiki/Bootstrap/blob/master/docs/release-notes.md#mediawiki-bootstrap-500) still uses Bootstrap 4.6.2. I realise the version numbering is confusing, but the idea was to create a new major version of the extension in order to remove support for old MW and fix support for new MW. The work to include Bootstrap 5.x in the Bootstrap extension is incomplete. That will likely end up being version 6.x of the extension.

Similarly, Chamelon master branch still uses Bootstrap 4.6.2.

**Comment by D3nnis3n** [comment]
> @D3nnis3n the current master is technically compatible with Bootstrap v5.0.0 which I recon you need for chameleon. If you check out the repo instead of using composer to install BootstrapComponents, you should be fine.
> 
> I'm still working on incorporating the changes in the components that come with bootstrap5.

All seems to work fine, thanks :)

**Comment by oetterer** [comment]
That is good to know, thanks. Was about to start switching the extension to bootstrap5 and would certainly run in some major headaches, wondering why the new component changes wont work.

**Comment by oetterer** [comment]
> All seems to work fine, thanks :)

Thanks for the feedback!

**Comment by oetterer** [comment]
closed by 00ca967ee2e4dff1ab7bf834c6769e93ee306ff2
